name: "godot-ci export"
on:
    push:
        branches: [ "main" ]

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: Web
  PROJECT_PATH: '.'
  ITCH_USERNAME: jcarnaxide
  ITCH_GAME_ID: platformer-with-brackeys

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ./build/web/index.html
      - name: Deploy to Itch.io 🚀
        uses: manleydev/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: html5
            ITCH_GAME: platformer-with-brackeys
            ITCH_USER: jcarnaxide
            PACKAGE: build/web
